version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodeapp
hooks:
  BeforeInstall:
    - location: scripts/deleteArtifacts.sh
      timeout: 500
      runas: root
  AfterInstall:
    - location: scripts/script.sh
      timeout: 500
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
