version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "No build process required"

  post_build:
    commands:
      - echo "Build phase complete"

artifacts:
  files:
    - '**/*'



